"""remove email field

Revision ID: 73d980c447c6
Revises: 84e7120607a6
Create Date: 2022-10-09 18:10:00.882753

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '73d980c447c6'
down_revision = '84e7120607a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='t_migrate_student')
    op.drop_column('t_migrate_student', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_migrate_student', sa.Column('email', mysql.VARCHAR(length=128), nullable=True, comment='邮箱地址'))
    op.create_index('email', 't_migrate_student', ['email'], unique=False)
    # ### end Alembic commands ###
